# Generated by Django 3.2.3 on 2021-06-02 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_listing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 6, 53, 33, 708518, tzinfo=utc)),
        ),
    ]
