# Generated by Django 3.2.3 on 2021-06-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_listing_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-created_at',)},
        ),
    ]
