# Generated by Django 3.2.3 on 2021-07-30 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210730_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='listings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.listing'),
        ),
    ]
