# Generated by Django 3.2.3 on 2021-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_cart_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
